### PR TITLE
fix the sourced test in shell script

### LINKED ISSUE #52: fails with "unsupported shell"  when sh is dash
On my system `/bin/sh` is dash shell.

Test for shell compatibility at the start of `pydockenv` binary fails since the script is started with `/usr/bin/env sh`

### PR DESCRIPTION
**Pull request by gaetano-guerriero**
Test was always failing, even on commands not intended to be called
with source, when the "sh" shell is dash.

fixes #52

### CODE REVIEW

**Comment by se7entyse7en** [comment]
Does this fix make it work on your system having dash as default shell? Doesn't it exist with unsupported shell error anyway? There's still no condition to check whether the script has been sourced for dash shell. Am I missing something?

Here are eventually some alternatives that I was thinking of:
1. completely remove the check as it seems that for example, conda doesn't perform any kind of this check too (I don't know whether virtualenv does),
2. add a condition for dash shell. This was taken from [here](https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced#answer-28776166), but I didn't include the case for POSIX-compliant version (honestly I don't understand that `case ${0##*/}` 😅).
3. change the shebang to use bash which should be the most available, but maybe it's not on alpine. And this could be a problem as I'm also planning to run pydockenv inside a container itself especially for development.

Honestly, I prefer to keep the check. That's because there's a difference between pydockenv and the other virtual env libraries. The others libraries when called without `source` should simply be no-ops (I'm guessing), but for pydockenv it won't set the env vars, but it will still start/stop the corresponding container. So it would be a bit counterintuitive. But obviously I'd like this to be working on most systems, so for now, even a sub-optimal solution could be fine.

One last thing is that closing #52 should also remove the need of [this line](https://github.com/se7entyse7en/pydockenv/blob/master/.travis.yml#L14).

WDYT? I'd like to know your opinion!

**Comment by gaetano-guerriero** [comment]
`source pydockenv activate` doesn't fail because script is sourced with the launching shell, the shebang is ignored.
`pydockenv activate` fails with "... must be called using 'source' with a supported shell".

Anyway this PR allows to call "create" on a machine having dash as `/bin/sh`, but activate still fails since "exit" on last line causes parent interactive shell to exit

**Comment by se7entyse7en** [comment]
> but activate still fails since "exit" on last line causes parent interactive shell to exit

Ouch! I actually didn't notice that this was causing the parent to exit! This was actually introduced by #47 and affects `v0.2.1` (latest version). So the idea is actually to use `return` in case of `source pydockenv {activate|deactivate}` and use `exit` for the others commands. It would be great if you could include this change in this PR!

So to recap, now the creation of an environment works even for dash shell. The activation works for bash, csh and zsh. Given that sourcing ignores the shebang I actually don't mind supporting dash also for `activate` and `deactivate`.

**Comment by gaetano-guerriero** [comment]
Added fix to skip `exit $exitCode` when script is sourced

**Comment by se7entyse7en** [comment]
I got `./bin/pydockenv: line 38: [: -eq: unary operator expected` locally, I get it fixed by initializing `sourced` to `0`, once you fix it I'm retesting and merging.

**Pull request merged**
